### ISSUE TITLE
How to get InternalLinks of a InterfaceClassType?

### ISSUE THREAD

**Issue by stefan-schweiger** [AutomationML/AMLEngine#1]
I've tried to multiple ways to get the InternalLinks fo an Interface, but none of those was successful. I even decompiled the AMLEditor and look into what the "find InternalLink Partner" action does (which works btw for this file in the editor), but as I can't figure out how to use this correctly.

Here are some stuff I've tried so far:

```C#
var document = CAEXDocument.LoadFromFile("File.aml");

InterfaceClassType @interface = ... // some implementation to get an specific interface

var links = _document.Tables.RegisteredReferences((CAEXBasicObject)@interface);
var links2 = _document.Tables
    .InternalLinkReferencesOfElement(@interface.GetParent<InternalElementType>());
var links3 = _document.Tables.InternalLinkPartners(@interface);
```

What's the accurate way of getting the InternalLinked interfaces?

**Comment by AutomationML** [comment]
Hallo Herr Schweiger,

die Tabellen können nur verwendet werden, wenn Sie selbst dafür sorgen, dass sie den aktuellen Inhalt des Dokumentes enthalten.
Zur Verwendung der Tabellen direkt nach dem Laden kann eine Update-Methode aufgerufen werden:

document.Tables.UpdateAllTables(false);

Diese Methode können Sie auch immer wieder aufrufen, wenn Änderungen im Dokument gemacht wurden. Es wird  dann aber immer
das gesamte Dokument durchsucht. Die Methode läuft daher optional auch als Hintergrundprozess. (parameter true).

Inkrementelle Updates können aber auch über separate Methoden gepflegt werden: AddCaexObject und RemoveCaexObject sind solche Methoden, wie in der Doku beschrieben.

Wenn die Tabellen aktuell sind können Sie mit folgender Methode arbeiten, um die InternalLink Referenzen auf ein Interface zu erhalten:

[cid:image002.png@01D080D1.BC5CE870]


Von: Stefan Schweiger [mailto:notifications@github.com]
Gesendet: Donnerstag, 23. April 2015 15:36
An: AutomationML/AMLEngine
Betreff: [AMLEngine] How to get InternalLinks of a InterfaceClassType? (#1)


I've tried to multiple ways to get the InternalLinks fo an Interface, but none of those was successful. I even decompiled the AMLEditor and look into what the "find InternalLink Partner" action does (which works btw for this file in the editor), but as I can't figure out how to use this correctly.

Here are some stuff I've tried so far:

var document = CAEXDocument.LoadFromFile("File.aml");



InterfaceClassType @interface = ... // some implementation to get an specific interface



var links = _document.Tables.RegisteredReferences((CAEXBasicObject)@interface);

var links2 = _document.Tables

    .InternalLinkReferencesOfElement(@interface.GetParent<InternalElementType>());

var links3 = _document.Tables.InternalLinkPartners(@interface);

What's the accurate way of getting the InternalLinked interfaces?
