### ISSUE TITLE
how to insert an element of type TypeBase

### ISSUE THREAD

**Issue by x1155665** [AutomationML/AMLEngine#3]
I have tried to use the method CAEXBasicObject.Insert_TypeBaseElement and InternalElementType.Insert_Element, but none of them worked.

Could you make examples to demonstrate the use of these Methods?

**Comment by AutomationML** [comment]
Please post your code

**Comment by x1155665** [comment]
The goal is to insert Templates in InternalElements.
The Content in Template can be anything: ExternalInterface, InternalElement, Attribute, InternalLink etc.

### Example:
#### Template (Template.xml):
```xml
<ExternalInterface Name="FileInterface" 
	ID="fc400fab-d7cc-4b31-9c28-45584bd743d3" >
	<Attribute Name="refURI" AttributeDataType="xs:anyURI">
		<Value>"./File"</Value>
	</Attribute>
</ExternalInterface>
```
#### AutomationML File (test.aml):
![default](https://cloud.githubusercontent.com/assets/11503677/17477849/f451a468-5d67-11e6-9b6a-64f0f2eee182.PNG)

#### Code:
```c#
var doc = new XmlDocument();
doc.Load("./Template.xml");
XmlNode templateNode = doc.DocumentElement;
var typeBaseObj = new TypeBase(templateNode);
var amlDoc = CAEXDocument.LoadFromFile("./test.aml");
var internalElement1 = amlDoc.CAEXFile.FindFastByID("ed894caa-a1eb-4369-9891-a50f77e79929");
bool result1 = internalElement1.Insert_TypeBaseElement(typeBaseObj);
bool result2 = ((InternalElementType)internalElement1).Insert_Element(typeBaseObj);
```
#### Result:
result1 and result2 are both false.


I think I have misunderstood the usages of these methods.
Could you give me some advice?
BTW, I am not sure, how to deal with the ID of the inserted element. The IDs in Template can not be carried directly into the AML file, right?

BTW, Sie können auf Deutsch antworten ;)

**Comment by AutomationML** [comment]
problem is, that the typebaseObj has not the proper Wrapper for insertion. Use CAEXBasicObject.CreateCaexWrapper (templateNode) to get the correct wrapper for insertion.

**Comment by x1155665** [comment]
Now I use the CAEXBasicObject.CreateCaexWrapper method.

```c#
var doc = new XmlDocument();
doc.Load("./Template.xml");
XmlNode templateNode = doc.DocumentElement;
var wrapper = CAEXBasicObject.CreateCAEXWrapper(templateNode);
var amlDoc = CAEXDocument.LoadFromFile("./test.aml");
var internalElement1 = amlDoc.CAEXFile.FindFastByID("ed894caa-a1eb-4369-9891-a50f77e79929");
bool result1 = internalElement1.Insert_TypeBaseElement(wrapper);
bool result2 = ((InternalElementType)internalElement1).Insert_Element(wrapper);
```

But an exception is thrown from 
`internalElement1.Insert_TypeBaseElement(wrapper);`
saying that the node comes from a different context.

**Comment by AutomationML** [comment]
Ja das ist der Fall, wenn der node aus einem anderen Dokument kommt. Bei XML ist das immer so, dass nicht so ohne weiteres ein XMLNode aus einem Dokument in ein anderes verschoben werden kann.

der weg in dem Beispiel wäre:

 var importedNode = amlDoc.CAEXFile.Node.OwnerDocument.ImportNode(templatedNode, true);

danach wie vorher.

**Comment by x1155665** [comment]
Vielen Dank für Ihre Hilfe!
